sudo: required
services:
  - docker

before_install:
  - docker build -t khacquyen1996/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khacquyen1996/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-666632162364"
  on: 
    branch: master